 
apiVersion: v1
kind: ConfigMap
metadata:
  name: is-skeletons-detector
  namespace: orchestrator
data:
  detector: |-
    {
      "broker_uri": "amqp://rabbitmq.orchestrator",
      "zipkin_host": "zipkin.orchestrator",
      "zipkin_port": 9411,
      "models_folder": "/models/",
      "model": "COCO",
      "network_resolution": {
        "width": -1,
        "height": 256
      },
      "output_resolution": {
        "width": -1,
        "height": -1
      },
      "scale_gap": {
        "value": 0.3
      },
      "scale_number": {
        "value": 1
      },
      "period": 5
    }