kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: is-skeletons-detector
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: is-skeletons-detector
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Object
      object:
        metricName: rabbitmq_msgs_per_second
        target:
          apiVersion: v1
          kind: Service
          name: SkeletonsDetector.Detection
        targetValue: 10
