apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: is-skeletons-detector
  labels:
    app: is-skeletons-detector
spec:
  namespaceSelector:
    matchNames:
      - orchestrator
  selector:
    matchLabels:
      app: is-skeletons-detector
  endpoints:
    - port: web
      interval: 5s # scrape the endpoint every X seconds