apiVersion: v1
kind: Service
metadata:
  name: is-skeletons-detector
  namespace: orchestrator
  labels:
    app: is-skeletons-detector
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: is-skeletons-detector