apiVersion: v1
kind: ConfigMap
metadata:
  name: is-orchestrator
  namespace: orchestrator
data:
  options: |-
    {
      "broker_uri": "amqp://rabbitmq.default"
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "is-orchestrator"
  namespace: orchestrator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: is-orchestrator
    spec:
      nodeSelector: 
        node-role.kubernetes.io/master: ""
      containers:
        - name: is-orchestrator
          image: luizcarloscf/is-orchestrator:0.0.1
          command: ["is-orchestrator"]
          args: ["/conf/options.json"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
          volumeMounts:
            - name: options
              mountPath: /conf/
            - name: config
              mountPath: /root/.kube/config
              readOnly: true
      volumes:
        - name: options
          configMap:
            name: is-orchestrator
            items:
              - key: options
                path: options.json
        - name: config
          hostPath:
            path: /etc/kubernetes/admin.conf
            type: File
