apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-skeletons-cpu"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: is-skeletons-cpu
    spec:
      containers:
        - name: is-skeletons-cpu
          image: luizcarloscf/is-skeletons-detector:0.0.3
          command: ["is-skeletons-detector-stream"]
          args: ["/opt/is/options.json"]
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            limits:
              cpu: "4"
              memory: 2048Mi
          volumeMounts:
            - name: options
              mountPath: /opt/is
      terminationGracePeriodSeconds: 1
      volumes:
      - name: options
        configMap:
          name: is-skeletons-cpu
          items:
          - key: detector
            path: options.json