apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: is-skeletons-cpu
  namespace: orchestrator
  labels:
    app: is-skeletons-cpu
spec:
  selector:
    matchLabels:
      app: is-skeletons-cpu
  endpoints:
    - port: web
      interval: 5s # scrape the endpoint every X seconds