apiVersion: v1
kind: Service
metadata:
  name: is-gesture-recognizer
  namespace: orchestrator
  labels:
    app: is-gesture-recognizer
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: is-gesture-recognizer
